[package]
name = "fastly-template-rust-default"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"